#!/usr/bin/env python
# -*- coding: utf-8 -*-

# ------------------------------------------------------------------------------------------------ #
# Automatically generated Python file defining classes for the enumerates from the EnumList sheet  #
# the CCTool-OO Schema file.                                                                       #
# ------------------------------------------------------------------------------------------------ #
# Compliant with Ref Sys 07-03-03-00                                                               #
# ------------------------------------------------------------------------------------------------ #


class WTF:
	Question_Mark = "?"


class PSDSide:
	DROITE = "DROITE"
	GAUCHE = "GAUCHE"
	GAUCHE_DROITE = "GAUCHE_DROITE"


class LineRightDirection:
	IMPAIR = "IMPAIR"


class LineLeftDirection:
	PAIR = "PAIR"


class YesOrNo:
	O = "O"
	N = "N"


class StoppingPointApproachType:
	CROISSANT = "CROISSANT"
	DECROISSANT = "DECROISSANT"
	DOUBLE_SENS = "DOUBLE_SENS"


class SegmentDirection:
	CROISSANT = "CROISSANT"
	DECROISSANT = "DECROISSANT"


class LineRelatedDirection:
	SENS_OPPOSE = "SENS_OPPOSE"
	SENS_LIGNE = "SENS_LIGNE"


class TrackPredominantDirection:
	G_a_D = "G->D"
	D_a_G = "D->G"


class Direction:
	CROISSANT = "CROISSANT"
	DECROISSANT = "DECROISSANT"


class TypeClasseObjetATSATC:
	QUAI = "QUAI"
	SIGNAL = "SIGNAL"
	SE = "SE"
	NV_PSR = "NV_PSR"


class TypeClasseObjetMESATS:
	SIGNAL = "SIGNAL"
	AIGUILLE = "AIGUILLE"


class TypeClasseObjetMESPAS:
	AIGUILLE = "AIGUILLE"
	SIGNAL = "SIGNAL"
	DP = "DP"
	CDV = "CDV"
	QUAI = "QUAI"
	SS = "SS"
	IXL_OVERLAP = "IXL_OVERLAP"
	PROTECTION_ZONE = "PROTECTION_ZONE"
	FLOOD_GATE = "FLOOD_GATE"
	IVB = "IVB"
	ASR = "ASR"
	TRAFFIC_STOP = "TRAFFIC_STOP"
	TSR_PREDEFINED_AREA = "TSR_PREDEFINED_AREA"
	PASSAGE_DETECTOR = "PASSAGE_DETECTOR"


class TypeClasseObjetPASATS:
	CDV = "CDV"
	DP = "DP"
	QUAI = "QUAI"
	AIGUILLE = "AIGUILLE"
	IVB = "IVB"
	ZAUM = "ZAUM"


class TypeClasseObjetPASMES:
	AIGUILLE = "AIGUILLE"
	SIGNAL = "SIGNAL"
	CDV = "CDV"
	QUAI = "QUAI"
	SS = "SS"
	IVB = "IVB"
	CROSSING_CALLING_AREA = "CROSSING_CALLING_AREA"
	PROTECTION_ZONE = "PROTECTION_ZONE"
	TSR_PREDEFINED_AREA_SPEED = "TSR_PREDEFINED_AREA_SPEED"


class TypeClasseObjetVariantBF:
	SIGNAL = "SIGNAL"
	QUAI = "QUAI"
	ZAUM = "ZAUM"
	NV_PSR = "NV_PSR"


class TypeClasseObjetVariantHF:
	AIGUILLE = "AIGUILLE"
	SIGNAL = "SIGNAL"
	QUAI = "QUAI"
	ZAUM = "ZAUM"
	FLOOD_GATE = "FLOOD_GATE"
	BLOCK = "BLOCK"
	ASR = "ASR"


class TypeClasseObjetFrontamGD:
	ADHESION_ZONE = "ADHESION_ZONE"


class TypeClasseReseau:
	STD_WCC = "STD_WCC"
	EQPT_SOL = "EQPT_SOL"
	ATS = "ATS"
	BROADCAST = "BROADCAST"
	ZONE_GEO = "ZONE_GEO"


class TypeClasseReseauGroupe:
	STD_WCC = "STD_WCC"
	EQPT_SOL = "EQPT_SOL"
	ATS = "ATS"
	BROADCAST = "BROADCAST"
	ZONE_GEO = "ZONE_GEO"
	CC = "CC"
	CRE = "CRE"


class TypeDA:
	SECTIONAL_RELEASE = "SECTIONAL_RELEASE"
	TRAIN_PASSAGE_PROVING = "TRAIN_PASSAGE_PROVING"


class DDType:
	REDONDE = "REDONDE"
	NON_REDONDE = "NON_REDONDE"


class VitalOrNotType:
	FONC = "FONC"
	SECU = "SECU"


class TypeMessageATSCBTC:
	ATS_PAE_TC_ENSEMBLE_ACTIONS = "ATS_PAE_TC_ENSEMBLE_ACTIONS"
	ATS_PAS_CTX_INTERDICTION_MODE = "ATS_PAS_CTX_INTERDICTION_MODE"
	ATS_PAS_CTX_ANNULATION_CRA = "ATS_PAS_CTX_ANNULATION_CRA"
	ATS_PAS_CTX_ZONES_EQUIP = "ATS_PAS_CTX_ZONES_EQUIP"
	ATS_PAS_CTX_ALIM_VS = "ATS_PAS_CTX_ALIM_VS"
	ATS_ZC_CTX_HOLDSKIP_PLATFORM = "ATS_ZC_CTX_HOLDSKIP_PLATFORM"
	ATS_ZC_CTX_NV_PSR_RELAXATION_CONDITION = "ATS_ZC_CTX_NV_PSR_RELAXATION_CONDITION"


class TypeMessageMESATS:
	MES_ATS_SUPERVISION = "MES_ATS_SUPERVISION"


class TypeMessageMESPAS:
	MES_PAS_ENTREES = "MES_PAS_ENTREES"
	OC_ZC_INPUTS_LONG = "OC_ZC_INPUTS_LONG"


class TypeMessagePASATS:
	PAS_ATS_SUPERVISION = "PAS_ATS_SUPERVISION"


class TypeMessagePASMES:
	PAS_MES_SORTIES = "PAS_MES_SORTIES"
	ZC_OC_OUTPUTS_LONG = "ZC_OC_OUTPUTS_LONG"


class TypeMessageVariantBF:
	PAS_PAE_VARIANTS_BF = "PAS_PAE_VARIANTS_BF"


class TypeMessageVariantHF:
	PAS_PAE_VARIANTS_HF = "PAS_PAE_VARIANTS_HF"


class TypeNomGroupe:
	SOL = "SOL"
	BORD = "BORD"


class TypeNomLogiqueInfoATSCBTC:
	QUAI_A_DESSERVIR = "QUAI_A_DESSERVIR"
	QUAI_DESTINATION = "QUAI_DESTINATION"
	CMCC_INTERDIT_DIR_IMPAIR = "CMCC_INTERDIT_DIR_IMPAIR"
	CPA_INTERDIT_DIR_IMPAIR = "CPA_INTERDIT_DIR_IMPAIR"
	CRA_INTERDIT_DIR_IMPAIR = "CRA_INTERDIT_DIR_IMPAIR"
	CMCC_INTERDIT_DIR_PAIR = "CMCC_INTERDIT_DIR_PAIR"
	CPA_INTERDIT_DIR_PAIR = "CPA_INTERDIT_DIR_PAIR"
	CRA_INTERDIT_DIR_PAIR = "CRA_INTERDIT_DIR_PAIR"
	ANNULATION_DEPART_CRA = "ANNULATION_DEPART_CRA"
	EN_PANNE = "EN_PANNE"
	ALIM_VS = "ALIM_VS"
	SAFETY_RELATED_HOLD_NORMAL_DIR = "SAFETY_RELATED_HOLD_NORMAL_DIR"
	SAFETY_RELATED_HOLD_REVERSE_DIR = "SAFETY_RELATED_HOLD_REVERSE_DIR"
	SAFETY_RELATED_SKIP_NORMAL_DIR = "SAFETY_RELATED_SKIP_NORMAL_DIR"
	SAFETY_RELATED_SKIP_REVERSE_DIR = "SAFETY_RELATED_SKIP_REVERSE_DIR"
	NV_PSR_RELAXATION_CONDITION = "NV_PSR_RELAXATION_CONDITION"


class TypeNomLogiqueInfoMESPAS:
	BLOCK = "BLOCK"
	SW_RIGHT_C = "SW_RIGHT_C"
	SW_LEFT_C = "SW_LEFT_C"
	IL_SET = "IL_SET"
	B_ESS = "B_ESS"
	PR_ASPECT = "PR_ASPECT"
	AP_CAN_RQ = "AP_CAN_RQ"
	B_TH = "B_TH"
	B_TAD = "B_TAD"
	DEPARTURE_AUTH = "DEPARTURE_AUTH"
	BLOCK_NORMAL_DIRECTION_L = "BLOCK_NORMAL_DIRECTION_L"
	BLOCK_REVERSE_DIRECTION_L = "BLOCK_REVERSE_DIRECTION_L"
	DD = "DD"
	TRACTION_PWR_REGEN_AUTH = "TRACTION_PWR_REGEN_AUTH"
	PROTECTION_LEVEL = "PROTECTION_LEVEL"
	B_ATB = "B_ATB"
	OLZ_OVERLAP_LK = "OLZ_OVERLAP_LK"
	MVT_AUTH = "MVT_AUTH"
	OPEN_AND_LOCKED = "OPEN_AND_LOCKED"
	FUNC_STOP_RQ = "FUNC_STOP_RQ"
	ASR_NOT_APPLIED = "ASR_NOT_APPLIED"
	UTO_MVT_AUTH = "UTO_MVT_AUTH"
	BLOCK_INIT_STATUS = "BLOCK_INIT_STATUS"
	STOP = "STOP"
	BLOCK_NOT_HELD = "BLOCK_NOT_HELD"
	TSR_AREA_SPEED_SET_CMD = "TSR_AREA_SPEED_SET_CMD"
	TSR_AREA_SPEED_REMOVE_CMD = "TSR_AREA_SPEED_REMOVE_CMD"
	NO_PASSAGE = "NO_PASSAGE"


class TypeNomLogiqueInfoPASATS:
	ETAT_CDV = "ETAT_CDV"
	ETAT_DP = "ETAT_DP"
	REGULATION_HOLD_NORMAL_DIR = "REGULATION_HOLD_NORMAL_DIR"
	REGULATION_SKIP_NORMAL_DIR = "REGULATION_SKIP_NORMAL_DIR"
	REGULATION_HOLD_REVERSE_DIR = "REGULATION_HOLD_REVERSE_DIR"
	REGULATION_SKIP_REVERSE_DIR = "REGULATION_SKIP_REVERSE_DIR"
	PREVENTS_EID = "PREVENTS_EID"
	MVT_AUTH = "MVT_AUTH"
	BRS_STATE = "BRS_STATE"
	BRSO_STATE = "BRSO_STATE"
	UTO_MVT_AUTH = "UTO_MVT_AUTH"
	SAFETY_RELATED_HOLD_REVERSE_DIR = "SAFETY_RELATED_HOLD_REVERSE_DIR"
	SAFETY_RELATED_HOLD_NORMAL_DIR = "SAFETY_RELATED_HOLD_NORMAL_DIR"
	SAFETY_RELATED_SKIP_REVERSE_DIR = "SAFETY_RELATED_SKIP_REVERSE_DIR"
	SAFETY_RELATED_SKIP_NORMAL_DIR = "SAFETY_RELATED_SKIP_NORMAL_DIR"
	AM_MVT_AUTH = "AM_MVT_AUTH"


class TypeNomLogiqueInfoPASMES:
	ZC_BLOCK = "ZC_BLOCK"
	TRAIN_PASS_HS = "TRAIN_PASS_HS"
	CBTC_APZ = "CBTC_APZ"
	STOP_ASSURE = "STOP_ASSURE"
	X_RQ = "X_RQ"
	TRAIN_AT_PLATFORM = "TRAIN_AT_PLATFORM"
	OPEN_CMD_L = "OPEN_CMD_L"
	OPEN_CMD_R = "OPEN_CMD_R"
	CLOSE_CMD_L = "CLOSE_CMD_L"
	CLOSE_CMD_R = "CLOSE_CMD_R"
	CBTC_OLZ = "CBTC_OLZ"
	TRAIN_IN_BERTH = "TRAIN_IN_BERTH"
	IXL_VIRTUAL_BLOCK = "IXL_VIRTUAL_BLOCK"
	BLOCK_FREED = "BLOCK_FREED"
	AUTHORIZED_NORMAL = "AUTHORIZED_NORMAL"
	AUTHORIZED_REVERSE = "AUTHORIZED_REVERSE"
	FUNC_STOP_ACCEPT = "FUNC_STOP_ACCEPT"
	FUNC_STOP_REJECT = "FUNC_STOP_REJECT"
	UNLOCK_DL_NORMAL = "UNLOCK_DL_NORMAL"
	UNLOCK_DL_REVERSE = "UNLOCK_DL_REVERSE"
	CBTC_FREE_TO_MOVE = "CBTC_FREE_TO_MOVE"
	CBTC_TRAIN_IN_APPROACH = "CBTC_TRAIN_IN_APPROACH"
	MOVEMENT_AUTHORIZED = "MOVEMENT_AUTHORIZED"
	POWER_AUTHORIZED = "POWER_AUTHORIZED"
	CROSSING_AUTH_REQUEST = "CROSSING_AUTH_REQUEST"
	TSR_AREA_SPEED_SUPERVISION = "TSR_AREA_SPEED_SUPERVISION"


class TypeNomLogiqueVariantBF:
	FAILED_ZONE = "FAILED_ZONE"
	T_ATP_MD_PROHIB_REVERSE_DIR = "T_ATP_MD_PROHIB_REVERSE_DIR"
	T_AD_PROHIB_REVERSE_DIR = "T_AD_PROHIB_REVERSE_DIR"
	T_ATB_PROHIB_REVERSE_DIR = "T_ATB_PROHIB_REVERSE_DIR"
	T_ATP_MD_PROHIB_NORMAL_DIR = "T_ATP_MD_PROHIB_NORMAL_DIR"
	T_AD_PROHIB_NORMAL_DIR = "T_AD_PROHIB_NORMAL_DIR"
	T_ATB_PROHIB_NORMAL_DIR = "T_ATB_PROHIB_NORMAL_DIR"
	PROTECTION_LEVEL = "PROTECTION_LEVEL"
	TRAIN_HOLD_NORMAL_DIR = "TRAIN_HOLD_NORMAL_DIR"
	TRAIN_HOLD_REVERSE_DIR = "TRAIN_HOLD_REVERSE_DIR"
	TRAIN_AHEAD_DEPARTURE = "TRAIN_AHEAD_DEPARTURE"
	SAFETY_RELATED_PLATFORM_HOLD_NORMAL_DIR = "SAFETY_RELATED_PLATFORM_HOLD_NORMAL_DIR"
	SAFETY_RELATED_PLATFORM_HOLD_REVERSE_DIR = "SAFETY_RELATED_PLATFORM_HOLD_REVERSE_DIR"
	SAFETY_RELATED_PLATFORM_SKIP_REVERSE_DIR = "SAFETY_RELATED_PLATFORM_SKIP_REVERSE_DIR"
	SAFETY_RELATED_PLATFORM_SKIP_NORMAL_DIR = "SAFETY_RELATED_PLATFORM_SKIP_NORMAL_DIR"
	NV_PSR_RELAXATION_CONDITION = "NV_PSR_RELAXATION_CONDITION"
	PLATFORM_SKIP_NORMAL_DIR = "PLATFORM_SKIP_NORMAL_DIR"
	PLATFORM_SKIP_REVERSE_DIR = "PLATFORM_SKIP_REVERSE_DIR"


class TypeNomLogiqueVariantHF:
	SW_RIGHT_C = "SW_RIGHT_C"
	SW_LEFT_C = "SW_LEFT_C"
	PR_ASPECT = "PR_ASPECT"
	IL_SET = "IL_SET"
	PLATFORM_ACCESS = "PLATFORM_ACCESS"
	ATB_DEP = "ATB_DEP"
	ATB_CAN_DEP = "ATB_CAN_DEP"
	MVT_AUTH = "MVT_AUTH"
	TRACTION_PWR_REGEN_AUTH = "TRACTION_PWR_REGEN_AUTH"
	UTO_MVT_AUTH = "UTO_MVT_AUTH"
	OPEN_AND_LOCKED = "OPEN_AND_LOCKED"
	FUNC_STOP_RQ = "FUNC_STOP_RQ"
	BLOCK_MVT_AUTH = "BLOCK_MVT_AUTH"
	AM_MVT_AUTH = "AM_MVT_AUTH"
	ASR_NOT_APPLIED = "ASR_NOT_APPLIED"


class TypeNomLogiqueFrontamGD:
	ADHESION_LEVEL = "ADHESION_LEVEL"


class DoorsOpeningSideType:
	DROITE = "DROITE"
	GAUCHE = "GAUCHE"
	DROITE_GAUCHE = "DROITE_GAUCHE"
	GAUCHE_DROITE = "GAUCHE_DROITE"


class StoppingPointType:
	AVANT = "AVANT"
	ARRIERE = "ARRIERE"
	CENTRE = "CENTRE"


class SiteSurveyType:
	PRECISE = "PRECISE"
	NON_PRECISE = "NON_PRECISE"


class DirectionZoneDefaultDir:
	CROISSANT = "CROISSANT"
	DECROISSANT = "DECROISSANT"


class DirectionZoneType:
	CROISSANT = "CROISSANT"
	DECROISSANT = "DECROISSANT"
	BLOCK_DIRECTION_LOCKING = "BLOCK_DIRECTION_LOCKING"


class SignalType:
	MANOEUVRE = "MANOEUVRE"
	ESPACEMENT = "ESPACEMENT"
	HEURTOIR = "HEURTOIR"
	PERMANENT_ARRET = "PERMANENT_ARRET"


class IATPMTagType:
	LOCAL = "LOCAL"
	RELEASE = "RELEASE"


class CBTCTerrType:
	EN_CBTC = "EN_CBTC"
	HORS_CBTC = "HORS_CBTC"
	OUTSIDE_CBTC_WITHIN_SDM = "OUTSIDE_CBTC_WITHIN_SDM"
	WITHIN_CBTC_WITHIN_DEPOT = "WITHIN_CBTC_WITHIN_DEPOT"


class TrackTypes:
	VOIE_1 = "VOIE_1"
	VOIE_2 = "VOIE_2"
	VOIE_COM = "VOIE_COM"
	VOIE_GAR = "VOIE_GAR"
	VOIE_3 = "VOIE_3"
	VOIE_4 = "VOIE_4"


class TypeZoneGeo:
	CELLULE = "CELLULE"
	TRONCON = "TRONCON"


class DrivingModesGroups:
	T_ATP_MD = "T_ATP_MD"
	T_AD = "T_AD"
	T_ATB = "T_ATB"
	NONE = "NONE"


class Edep_Type:
	NO_CBTC_REQUEST = "NO_CBTC_REQUEST"


class Switch_Position:
	DROITE = "DROITE"
	GAUCHE = "GAUCHE"


class IXL_Direction:
	NORMAL = "NORMAL"
	REVERSE = "REVERSE"


class ConcealType:
	NONE = "NONE"
	WAVE = "WAVE"
	ALL_DARK = "ALL_DARK"


class Cab_Enum:
	CAB1 = "CAB1"
	CAB2 = "CAB2"


class Polarity_Enum:
	POSITIVE = "POSITIVE"
	NEGATIVE = "NEGATIVE"


class OC_Enum:
	ACC = "ACC"
	MLK = "MLK"


class VSPType:
	CIVIL_INFRASTRUCTURE = "CIVIL_INFRASTRUCTURE"
	OTHERS = "OTHERS"


class ProtectionZoneType:
	IXL = "IXL"
	STES = "STES"
	CENTRAL_ESS = "CENTRAL_ESS"
	INTRUDER = "INTRUDER"
	WORK_ZONE = "WORK_ZONE"
	CBTC_PROTECTION_ZONE = "CBTC_PROTECTION_ZONE"
	PSD_ALARM = "PSD_ALARM"


class OSPType:
	AT_PLATFORM = "AT_PLATFORM"
	OUT_OF_PLATFORM = "OUT_OF_PLATFORM"


class UWAType:
	WHOLE = "WHOLE"
	FRONT = "FRONT"


class UWACause:
	OVERSWITCH = "OVERSWITCH"
	RESCUE_TROLLEY = "RESCUE_TROLLEY"
	GAP = "GAP"
	OTHERS = "OTHERS"


class UWADir:
	POSITIVE = "POSITIVE"
	NEGATIVE = "NEGATIVE"
	BOTH = "BOTH"


class ForcedNo:
	N = "N"


class PV_TractionType:
	ALL_VITAL = "ALL_VITAL"
	ALL_NON_VITAL = "ALL_NON_VITAL"
	VITAL_MANUAL_ONLY = "VITAL_MANUAL_ONLY"


class SievingLimitType:
	BLOCK = "BLOCK"
	BUFFER = "BUFFER"


class NV_PSR_Relaxation_Cause:
	NO_WASHING = "NO_WASHING"
	WITH_ACTIVE_CCTV = "WITH_ACTIVE_CCTV"


class PV_AuxiliaryVehicleConsistType:
	PV_TYPE_1 = "PV_TYPE_1"
	PV_TYPE_2 = "PV_TYPE_2"


class AV_AuxiliaryVehicleConsistType:
	AV_TYPE_1 = "AV_TYPE_1"
	AV_TYPE_2 = "AV_TYPE_2"
	AV_TYPE_3 = "AV_TYPE_3"


class AV_TractionType:
	ALL_NON_VITAL = "ALL_NON_VITAL"
	VITAL_MANUAL_ONLY = "VITAL_MANUAL_ONLY"


class FB_AuxiliaryVehicleConsistType:
	FLATBED_TYPE_1 = "FLATBED_TYPE_1"
	FLATBED_TYPE_2 = "FLATBED_TYPE_2"
	FLATBED_TYPE_3 = "FLATBED_TYPE_3"
	FLATBED_TYPE_4 = "FLATBED_TYPE_4"


class ChainageType:
	GAP = "GAP"
	RECOVERY = "RECOVERY"


class TagReadingOccurence:
	OFTEN_READ = "OFTEN_READ"
	RARELY_READ = "RARELY_READ"
	VERY_RARELY_READ = "VERY_RARELY_READ"


class TrainTypeDegradedModeEnum:
	SDM = "SDM"
	IATPM = "IATPM"


class DynamicBrakeType:
	EB = "EB"
	FSB = "FSB"


class RadioCoverageType:
	FULL = "FULL"
	PARTIAL = "PARTIAL"
	UNAVAILABLE = "UNAVAILABLE"


class CcIsolationInputType:
	DEDICATED_INPUT = "DEDICATED_INPUT"
	BYPASS_RELAY_FEEDBACK = "BYPASS_RELAY_FEEDBACK"
	DRIVER_MODE_SWITCH = "DRIVER_MODE_SWITCH"


class InterCCComType:
	WIRED = "WIRED"
	WIRELESS = "WIRELESS"


class UWAApplicability:
	STANDARD = "STANDARD"
	RECOVERY = "RECOVERY"
	BOTH = "BOTH"


class OSPooP_Opening_Side:
	NONE = "NONE"
	RIGHT = "RIGHT"
	LEFT = "LEFT"
	BOTH = "BOTH"


class ZA_EFF_T_Trigger:
	TRAIN_PRESENCE = "TRAIN_PRESENCE"
	ONE_COLLECTOR = "ONE_COLLECTOR"
	ALL_COLLECTORS = "ALL_COLLECTORS"


class ZA_EFF_T_Type:
	POWER_SUPPLY_GAP = "POWER_SUPPLY_GAP"
	OTHER = "OTHER"


class ASRDir:
	POSITIVE = "POSITIVE"
	NEGATIVE = "NEGATIVE"
	BOTH = "BOTH"


class BitOrByteType:
	BIT = "BIT"
	BYTE = "BYTE"


class MasterControllerType:
	EFFORT_DRIVEN = "EFFORT_DRIVEN"
	SPEED_DRIVEN = "SPEED_DRIVEN"


class UCADir:
	POSITIVE = "POSITIVE"
	NEGATIVE = "NEGATIVE"
	BOTH = "BOTH"


class Odometry_Level:
	LEVEL1 = "LEVEL1"
	LEVEL2 = "LEVEL2"
