#!/usr/bin/env python
# -*- coding: utf-8 -*-

from ..database_location import *


if PROJECT_NAME == Projects.Brussels:
    LOC_DICT = {
        "Name_Title":                             {"x":  42, "y": 814, "x_tol": 30, "y_tol": 30},
        "Name":                                   {"x": 115, "y": 813, "x_tol": 40},
        "[1a] Controlled Signal":                 {"x":  44, "y": 736},
        "[1b] Origin LED Matrix":                 {"x":  44, "y": 636},
        "[2] Incompatibilities":                  {"x": 222, "y": 765, "y_tol": 40},
        "[5] Route path":                         {"x": 226, "y": 630, "y_tol": 60},
        "[6] Flank protections":                  {"x": 307, "y": 630, "y_tol": 60},
        "[7] External Conditions":                {"x": 464, "y": 362},
        "[8] Flank protections":                  {"x": 372, "y": 510, "x_tol": 40, "y_tol": 70},
        "[9] Route path":                         {"x": 230, "y": 510, "y_tol": 70},
        "[10] Route path (T.C. clearance)":       {"x":  48, "y": 487, "y_tol": 40},
        "[12] Overlap set":                       {"x":  49, "y": 395, "y_tol": 40},
        "[14] Approach Area clearance":           {"x": 232, "y": 329},
        "[15] External Conditions":               {"x": 464, "y": 362},
        "[16] Route path (T.C. clearance)":       {"x": 221, "y": 180, "y_tol": 40},
        "[17] Flank protection (T.C. clearance)": {"x": 340, "y": 183, "x_tol": 30, "y_tol": 40},
        "[18] Track Circuit clearance":           {"x": 485, "y": 195},
        "[19] External Conditions":               {"x":  47, "y": 260, "y_tol": 80},
    }
elif PROJECT_NAME == Projects.Copenhagen:
    LOC_DICT = {
        "Name_Title":                             {"x":  55, "y": 752, "x_tol": 30, "y_tol": 30},
        "Name":                                   {"x": 122, "y": 750, "x_tol": 40},
        "[1] Controlled Signal":                  {"x":  43, "y": 676},
        "[2] Incompatibilities":                  {"x": 218, "y": 704, "y_tol": 40},
        "[3] Route Path":                         {"x": 339, "y": 673},
        "[4] Flank protections":                  {"x": 451, "y": 672},
        "[5] Route path":                         {"x": 221, "y": 550},
        "[6] Flank protections":                  {"x": 301, "y": 551},
        "[7] External Conditions":                {"x": 421, "y": 573},
        "[8] Flank protections":                  {"x": 384, "y": 422},
        "[9] Route path":                         {"x": 226, "y": 423},
        "[10] Route path (T.C. clearance)":       {"x":  47, "y": 582},
        "[11] Functions not activated":           {"x":  48, "y": 494},
        "[12] Overlap set":                       {"x":  48, "y": 432},
        "[13] Permanent Replacement T.C.":        {"x": 228, "y": 279},
        "[14] Approach Area clearance":           {"x": 360, "y": 283},
        "[15] External Conditions":               {"x": 450, "y": 309},
        "[16] Route path (T.C. clearance)":       {"x": 225, "y": 196},
        "[17] Flank protection (T.C. clearance)": {"x": 343, "y": 192},
        "[18] Track Circuit clearance":           {"x": 475, "y": 184},
        "[19] External Conditions \\ MAR":        {"x":  47, "y": 364, "y_tol": 50},
    }
elif PROJECT_NAME == Projects.Glasgow:
    LOC_DICT = {
        "Name_Title":                             {"x":  44, "y": 814, "x_tol": 30, "y_tol": 30},
        "Name":                                   {"x": 132, "y": 812, "x_tol": 40},
        "[1] Origin Signal":                      {"x":  47, "y": 736},
        "[2] Incompatibilities":                  {"x": 224, "y": 765},
        "[3] Route Path":                         {"x": 349, "y": 733},
        "[4] Flank protections":                  {"x": 463, "y": 733},
        "[5] Route path":                         {"x": 228, "y": 608},
        "[6] Flank protections":                  {"x": 309, "y": 609},
        "[7] External Conditions":                {"x": 432, "y": 632},
        "[8] Flank protections":                  {"x": 394, "y": 476},
        "[9] Route path":                         {"x": 233, "y": 478},
        "[10] Route path (T.C. clearance)":       {"x":  50, "y": 600},
        "[11] Functions not activated":           {"x":  50, "y": 504},
        "[12] Overlap set":                       {"x":  51, "y": 416},
        "[13] Permanent Replacement T.C.":        {"x": 234, "y": 325},
        "[14] Approach Area clearance":           {"x": 370, "y": 329},
        "[15] External Conditions":               {"x": 467, "y": 362},
        "[16] Route path (T.C. clearance)":       {"x": 232, "y": 208},
        "[17] Flank protection (T.C. clearance)": {"x": 364, "y": 203},
        "[18] Track Circuit clearance":           {"x": 488, "y": 203},
        "[19] External Conditions":               {"x":  49, "y": 313, "y_tol": 50},
    }
elif PROJECT_NAME == Projects.Milan:
    LOC_DICT = {
        "Name_Title":                             {"x":  56, "y": 750, "x_tol": 30, "y_tol": 30},
        "Name":                                   {"x": 125, "y": 748, "x_tol": 40},
        "[1] Controlled Signal":                  {"x":  44, "y": 672},
        "[2] Incompatibilities":                  {"x": 222, "y": 675, "y_tol": 40},
        "[3] Route Path":                         {"x": 346, "y": 660, "y_tol": 30},
        "[4] Flank protections":                  {"x": 460, "y": 668},
        "[5] Route path":                         {"x": 226, "y": 544},
        "[6] Flank protections":                  {"x": 307, "y": 520, "y_tol": 50},
        "[7] External Conditions":                {"x": 429, "y": 568},
        "[8] Flank protections":                  {"x": 391, "y": 400, "y_tol": 40},
        "[9] Route path":                         {"x": 230, "y": 400, "y_tol": 40},
        "[10] Route path (T.C. clearance)":       {"x":  48, "y": 520, "y_tol": 40},
        "[11] Functions not activated":           {"x":  48, "y": 446},
        "[12] Overlap set":                       {"x":  48, "y": 383},
        "[13] Permanent Replacement T.C.":        {"x": 232, "y": 260},
        "[14] Approach Area clearance":           {"x": 352, "y": 271},
        "[15] External Conditions":               {"x": 459, "y": 298},
        "[16] Route path (T.C. clearance)":       {"x": 229, "y": 160, "y_tol": 50},
        "[17] Flank protection (T.C. clearance)": {"x": 350, "y": 178},
        "[18] Track Circuit clearance":           {"x": 485, "y": 154},
        "[19] External Conditions \\ MAR":        {"x":  47, "y": 290, "y_tol": 60},
    }
elif PROJECT_NAME == Projects.Riyadh:
    LOC_DICT = {
        "Name_Title":                             {"x":  38, "y": 814, "x_tol": 30, "y_tol": 30},
        "Name":                                   {"x": 103, "y": 812, "x_tol": 40},
        "[1] Controlled Signal":                  {"x":  44, "y": 736},
        "[2] Incompatibilities":                  {"x": 222, "y": 755, "y_tol": 40},
        "[3] Route Path":                         {"x": 346, "y": 733},
        "[4] Flank protections":                  {"x": 460, "y": 733},
        "[5] Route path":                         {"x": 226, "y": 608},
        "[6] Flank protections":                  {"x": 307, "y": 609},
        "[7] External Conditions":                {"x": 430, "y": 632},
        "[8] Flank protections":                  {"x": 392, "y": 476},
        "[9] Route path":                         {"x": 230, "y": 478},
        "[10] Route path (T.C. clearance)":       {"x":  48, "y": 600},
        "[11] Functions not activated":           {"x":  48, "y": 507},
        "[12] Overlap set":                       {"x":  49, "y": 430, "y_tol": 40},
        "[13] Permanent Replacement T.C.":        {"x": 232, "y": 325},
        "[14] Approach Area clearance":           {"x": 367, "y": 336},
        "[15] External Conditions":               {"x": 464, "y": 362},
        "[16] Route path (T.C. clearance)":       {"x": 229, "y": 208},
        "[17] Flank protection (T.C. clearance)": {"x": 362, "y": 203},
        "[18] Track Circuit clearance":           {"x": 485, "y": 203},
        "[19] External Conditions":               {"x":  47, "y": 340, "y_tol": 50},
        "[20] Downstream T.C.":                   {"x": 367, "y": 320},
    }
elif PROJECT_NAME == Projects.Thessaloniki:
    LOC_DICT = {
        "Name_Title":                             {"x":  37, "y": 815, "x_tol": 30, "y_tol": 30},
        "Name":                                   {"x": 114, "y": 813, "x_tol": 40},
        "[1] Controlled Signal":                  {"x":  43, "y": 739},
        "[2] Incompatibilities":                  {"x": 218, "y": 750, "y_tol": 40},
        "[3] Route Path":                         {"x": 339, "y": 710, "y_tol": 40},
        "[4] Flank protections":                  {"x": 451, "y": 735},
        "[5] Route path":                         {"x": 221, "y": 613},
        "[6] Flank protections":                  {"x": 301, "y": 614},
        "[7] External Conditions":                {"x": 421, "y": 636},
        "[8] Flank protections":                  {"x": 384, "y": 484},
        "[9] Route path":                         {"x": 226, "y": 485},
        "[10] Route path (T.C. clearance)":       {"x":  47, "y": 605},
        "[11] Functions not activated":           {"x":  47, "y": 511},
        "[12] Overlap set":                       {"x":  48, "y": 424},
        "[13] Permanent Replacement T.C.":        {"x": 227, "y": 336},
        "[14] Approach Area clearance":           {"x": 360, "y": 340, "y_tol": 15},
        "[15] External Conditions":               {"x": 455, "y": 372},
        "[16] Route path (T.C. clearance)":       {"x": 225, "y": 221, "y_tol": 40},
        "[17] Flank protection (T.C. clearance)": {"x": 355, "y": 216, "y_tol": 40},
        "[18] Track Circuit clearance":           {"x": 476, "y": 210},
        "[19] External Conditions":               {"x":  46, "y": 314, "y_tol": 40},
        "[20] Downstream T.C.":                   {"x": 360, "y": 290},
    }
else:  # default
    LOC_DICT = {
        "Name_Title":                             {"x":  44, "y": 814, "x_tol": 30, "y_tol": 30},
        "Name":                                   {"x": 132, "y": 812, "x_tol": 40},
        "[1] Origin Signal":                      {"x":  47, "y": 736},
        "[2] Incompatibilities":                  {"x": 224, "y": 765},
        "[3] Route Path":                         {"x": 349, "y": 733},
        "[4] Flank protections":                  {"x": 463, "y": 733},
        "[5] Route path":                         {"x": 228, "y": 608},
        "[6] Flank protections":                  {"x": 309, "y": 609},
        "[7] External Conditions":                {"x": 432, "y": 632},
        "[8] Flank protections":                  {"x": 394, "y": 476},
        "[9] Route path":                         {"x": 233, "y": 478},
        "[10] Route path (T.C. clearance)":       {"x":  50, "y": 600},
        "[11] Functions not activated":           {"x":  50, "y": 504},
        "[12] Overlap set":                       {"x":  51, "y": 416},
        "[13] Permanent Replacement T.C.":        {"x": 234, "y": 325},
        "[14] Approach Area clearance":           {"x": 370, "y": 329},
        "[15] External Conditions":               {"x": 467, "y": 362},
        "[16] Route path (T.C. clearance)":       {"x": 232, "y": 208},
        "[17] Flank protection (T.C. clearance)": {"x": 364, "y": 203},
        "[18] Track Circuit clearance":           {"x": 488, "y": 203},
        "[19] External Conditions":               {"x":  49, "y": 313, "y_tol": 50},
    }


def loc_info_pdf_route():
    loc_dict = LOC_DICT
    return loc_dict
